package com.bank.credit.card.api.service;

import com.bank.credit.card.api.model.Card;
import com.bank.credit.card.api.repository.CardRepository;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;


/**
 * CreditCardServiceImpl service is responsible for service credit card data.
 * <p> This service serves functionality to add new credit card in data repository</p>
 * <p> This service serves functionality to fetch all existing credit card from data repository</p>
 */

@Service
@Slf4j
public class CreditCardServiceImpl implements CardService {

    CardRepository cardRepository;

    @Autowired
    CreditCardServiceImpl(CardRepository cardRepository){
        this.cardRepository = cardRepository;
    }

    /**
     * This operation should be used when new credit card is to be store in backend system.
     * @param card : Credit Card object which need to be store in backend system
     * @return : Updated details of card with unique ID generated by backend system.
     */
    @Override
    public Card addCard(Card card) {
        log.debug("Add credit card started");
        return cardRepository.save(card);
    }

    /**
     * This operation should be used when all credit card is to be fetch from backend system
     * @return : List of all credit card
     */
    @Override
    public List<Card> findAll() {
        log.debug("Fetch all credit card started");
        return cardRepository.findAll();
    }
}
